The ipmgr failures in the postinst script are problematic, making it a warning instead.

diff --git a/debian/ipmgr.postinst b/debian/ipmgr.postinst
--- a/debian/ipmgr.postinst
+++ b/debian/ipmgr.postinst
@@ -30,7 +30,10 @@ then
     # In most cases, it's not useful to run ipmgr on the first install,
     # but on subsequent installations, it may be necessary to update the
     # files to the latest version
-    ipmgr
+    if ! ipmgr
+    then
+        echo "warning: ipmgr failed, please make sure bind is up and running."
+    fi
 
     if systemctl is-active named
     then
